force-app/main/default/objects/Order/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>This field is used to calculate Due date on the basis of Activation date + Payment Terms</description>
    <formula>IF(NOT(ISNULL( ActivatedDate )) ,  IF( PaymentTerms__c &gt; 0  ,   ActivatedDate + PaymentTerms__c ,   ActivatedDate  ) , Null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/TaskCreated__c.field-meta.xml
<CustomField>
    <fullName>TaskCreated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Is used to check orde has already task or not</description>
    <label>Task Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>This Field is used to calculate the Complete total amount including Tax , Shipping fees and Order Amount</description>
    <formula>IF(RecordType.Name = &apos;Credit Memo&apos;, -1  * ( NetAmount__c  + ShippingFees__c +  CreditMemoAmount__c -  DiscountAmount__c ),  ( NetAmount__c + ShippingFees__c) -  DiscountAmount__c + CreditMemoOrderAmount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Net amount + Shipping fees - Payment Discount - Credit Memo</inlineHelpText>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentReminderBatch.cls
/**
Name                   :        PaymentReminderBatch         
Author                 :        Infoglen
Date                   :        24th September, 2020
Description            :        This Class is Used to create task On due date
**/

global class PaymentReminderBatch implements  Database.Batchable<sObject>{
    //Start Method
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        // collect the Refferral discount records to be passed to execute
        String query = 'SELECT Id,Total_Amount__c,AccountId,opportunityId FROM order WHERE Status =\'Activated\' AND  DueDate__c = Today AND TaskCreated__c = False AND Total_Amount__c > 0';
        return Database.getQueryLocator(query);
        
        
    }
    //Execute Method
    global void execute(Database.BatchableContext bc, List<Order> oredrList){
        
        Map<Id,Id> orderWithOpportunityId = new Map<Id,Id>();
        List<Task> tasksToInsert =  new List<Task>();
        
        For(Order orderObj : oredrList ){
            orderWithOpportunityId.put(orderObj.Id,orderObj.OpportunityId);
        }
        
        if(orderWithOpportunityId.size() > 0){
            //Getting Task 
            tasksToInsert = WlUtility.taskCreationOnOrder(orderWithOpportunityId,True);
        }
        
        if(tasksToInsert.size() > 0){
            Database.SaveResult[] taskList = Database.insert(tasksToInsert, false);
            system.debug('taskList--->'+taskList);
        }
        
        
    }
    global void finish(Database.BatchableContext BC){
    }
}